import Footer from "@/components/shared/Footer";
import ScrollToTopButton from "@/components/shared/ScrollToTopButton";
import Socials from "@/components/shared/Socials";
import { StickyNav } from "@/components/shared/StickyNav";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { Spotlight } from "@/components/ui/spotlight";
import { geistMono, geistSans, incognito } from "./fonts/font";
import "./globals.css";
import LoadingWrapper from "./LoadingWrapper";

export const metadata = {
  title: "Rejoyan Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${incognito.variable} relative scroll-smooth antialiased text-primary bg-background-secondary overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        <LoadingWrapper>
          <ThemeProvider
            enableSystem
            attribute="class"
            defaultTheme="light"
            themes={[
              "light",
              "dark",
              // "instagram",
              // "facebook",
              // "discord",
              // "netflix",
              // "twilight",
              // "reddit",
            ]}
          >
            <StickyNav />

            <Spotlight
              className="top-40 left-0 md:left-96 md:top-0 z-50  "
              fill="rgba(16, 163, 233, .7)"
            />

            <main className="mx-auto max-container  px-4">{children}</main>
            <Socials direction="col" position="fixed" />
            <ScrollToTopButton />
            <Footer />
          </ThemeProvider>
        </LoadingWrapper>
      </body>
    </html>
  );
}
